### PR TITLE
Fixes GraphQL query serialization (#364)

### LINKED ISSUE #364: Input strings containing single quote characters needlessly escaped with "\"
Single quote characters appearing in input string arguments are incorrectly escaped with `\`. According to the GraphQL specification, this is not necessary. JSON specification doesn't require this either.
This problem causes the JSON parser in my GraphQL server to fail.

My example GraphQL:
```
mutation {
  customers {
    clear
    load(
      values:[
        { customerId: 197, firstName: "Andy", lastName: "O'neill",
          phone: null, email: "andy.o'neill@msn.com",
          street: "9544 Mulberry Drive ",city: "Rego Park",
          state: "NY", zipCode: 11374
        },
      ]
    )
  }
}
```

The http POST request generated by executing this query in the GraphQL editor is as follows:
`{"query":"mutation {\n  customers {\n    clear\n    load(\n      values:[\n        { customerId: 197, firstName: \"Andy\", lastName: \"O\'neill\", phone: null, email: \"andy.o\'neill@msn.com\", street: \"9544 Mulberry Drive \", city: \"Rego Park\", state: \"NY\", zipCode: 11374 },\n      ]\n    )\n  }\n}", "variables":null}`

You can see that the single quote in `"O'neill"` is escaped as `\"O\'neill\"`. But, this is not necessary. It will cause standard compliant JSON parsers to fail.

Regards,
VN

### PR DESCRIPTION
**Pull request by vepanimas**
Fixes #364

A bit of the issue history: #64, #86

### CODE REVIEW

File: src/main/com/intellij/lang/jsgraphql/v1/ide/project/JSGraphQLLanguageUIProjectService.java [hunk 1]
```diff
@@ -455,6 +453,26 @@ public void run(@NotNull ProgressIndicator indicator) {
         }
     }
 
+    @NotNull
+    private static Gson createQueryJsonSerializer() {
```
Comment (anstarovoyt) [inline src/main/com/intellij/lang/jsgraphql/v1/ide/project/JSGraphQLLanguageUIProjectService.java:457]: can be a static field

**Review by anstarovoyt — APPROVED** [review]
